dataset_model:      
  dataset_model_pair_name: "Cifar100-DenseNet121"     # options: "Cifar10-ResNet50", "Cifar10-ResNet34", "Cifar100-ResNet50", "Cifar100-DenseNet121", "ImageNet-ResNet152", "ImageNet-ViT"
  device: "cpu"  # options: "cpu", "cuda"


conformal:
  n: 1000            # number of samples used for the CP procedure 
  alpha: 0.1
  device: "cpu"
  method: "RAPS"     # options: "LAC", "APS", "RAPS"
  lam_reg: 0.01      # only used by RAPS
  k_reg: 5           # only used by RAPS


ts4cp:
  n_eval: 1000
  beta: 0
    # beta is the trade-off parameter between AvgSize and TopCovGap which is user-configurable and takes values in the range [0, 1]. 
    # Setting beta = 0 corresponds to optimizing the temperature for AvgSize, while beta = 1 corresponds to optimizing for TopCovGap.
